### ISSUE TITLE
Image depth of Dicom files

### ISSUE THREAD

**Issue by dpetrini** [vinbigdata-medical/vindr-mammo#1]
Hi,

Thanks for the awesome work of provinding Vindr-Mammo dataset.

I have a doubt, if I analyse the dicom image in ImageJ software I can see image depth is 12 bits.
However, if I apply script visualize.py to convert the image to png and save it, the resulting image is 8 bits.

I wonder if the original image is 12 or 8 bits actually.

I guess this script works only for visualization right?
And for prepare the file for further ML training we have to convert full image with 12 bits.

**Comment by hieu1999210** [comment]
You are right. For training, using the original dynamic range of the image would be better than the 8-bit range.
